### ISSUE TITLE
Possible memory leak with new version of VueMeta@2

### ISSUE THREAD

**Issue by LuXDAmore** [ymmooot/nuxt-jsonld#123]
Updating `nuxt@2.9.2` and `vue-meta@2.2.0`, and browsing the website, cause Google Chrome to crash.

You can see what's happening [here](https://github.com/nuxt/nuxt.js/issues/6338#issuecomment-531751641).

I'm trying to reproduce the issue in this [codesandbox](https://codesandbox.io/s/nuxt-vue-meta-220-bug-rrd1z).

**Comment by pimlie** [comment]
The issue is that this module adds a global mixin which adds a `head()` used on _all_ Vue components. The [nuxt-i18n docs](https://nuxt-community.github.io/nuxt-i18n/seo.html#improving-performance) write why that a potential performance issue

Besides the approach nuxt-i18n of letting the user merge meta info, starting with `v2.3` it will be possible to inject metaInfo into vue-meta without going through a component. You can read about that in this pr here: https://github.com/nuxt/vue-meta/pull/452#issue-317111661

A beta for `v2.3` has already been released, so please feel free to try that out.

**Comment by ymmooot** [comment]
Thank you for the information. 🙏 
I will fix it.

**Comment by pimlie** [comment]
Thank you for this plugin!

Btw, maybe it would also be interesting to convert this plugin to a [module](https://nuxtjs.org/guide/modules)? That way people only have to add an entry to the module section in their nuxt.config and they dont have to create their own plugin.

Just tag me if you need help with that or would like a review.

**Comment by Zsavajji** [comment]
A bit unrelated to the issue, but what would be the correct way to push some meta in a module? @pimlie

**Comment by ymmooot** [comment]
@pimlie Thank you so much.
I want to convert this plugin to a module in next major version.
I will tell you when I make a module version!

**Comment by pimlie** [comment]
@Zsavajji It probably depends on the kind of meta information you want to push, or better do you need Vue's reactivity or not? In most cases you will need that so your meta info changes on navigation.

In the current stable vue-meta there isnt really a good way of injecting independent meta info from within a module. With `v2.3` the recommended approach will be:

- add a plugin
- let that plugin insert a global mixin
- the mixin should only contain a beforeCreate and destroyed hook
- in the beforeCreate hook check if the component is a relevant component for your module, if so add a created or mounted hook for that component in which you add meta info using vue-meta's new addApp method
- in the destroyed hook, remove the meta-info if needed

Also do this for the activated/deactivated hooks if needed. You can look at the vue-meta createMixin  method how to do this as its basically the same approach.

But please note that `v2.3` is still beta, would appreciate feedback if the addApp feature works well in practice or that some changes are needed. 
Also note my previous comment about the need of your plugin's mixin to be run before vue-meta's. If thats really difficult to do in practice, we should have a look if we need to either change Nuxt or Vue-Meta to make that easier

**Comment by Zsavajji** [comment]
Very detailed answer, thank you. 
So your advice is still to use a global mixin, to dynamically insert meta with the new `v2.3` methods. 
I'm asking cause i saw other ways in modules i'm using, like reassigning the `head` property of a component in the plugin, and i was curious about what would the _best_ way of doing that was in your opinion.
By sticking to older versions though, wouldn't it be enough to add the custom meta in the `metaInfo` property (still with a mixin, checking if the component is relevant) and then let vue-meta do the necessary merges?

**Comment by pimlie** [comment]
> So your advice is still to use a global mixin

Yes, but the difference being that the global mixin _only_ adds a beforeCreate hook (and currently destroyed due to the memory leak in vue). Within that hook you then first check if the component is relevant to your module, and only if it is you add the hooks which will do the actual work.

Not sure how / if / when reassigning `head` works, which modules are you referring to? If `head` is a function then I think it should be done before vue-meta initializes for that component (hence the before mentioned beforeCreate hierarchy) because otherwise vue-meta will already use the original `head` ref as computed prop. But not fully sure about that. If `head` is an object you should be able to just re-assign it indeed.
None of the above is an official recommendation though, there just isnt an official recommendation of what to do in previous versions unfortunately. There didnt exist a proper method do inject metaInfo from a nuxt module into a page component so anything thats currently used is considered unsupported behaviour (again no guarantees, but we will try not to break it until a next major).

**Comment by Zsavajji** [comment]
I may have found out how to patch head the correct way, and i'll submit a PR later, if i get typescript sorted out 😂

**Comment by AndrewBogdanovTSS** [comment]
@ymmooot after I upgraded to `vue-meta@2.3.0-beta.0` and `nuxt-jsonld@1.4.4` performance has increased drastically compared to the previous version, no memory leak I can observe by now. Will let you know if I'll stumble upon something in the future. Thanks a lot for the fix! 🎉

**Comment by Zsavajji** [comment]
`vue-meta@2.3` should not be required, as we're not using any features of the new version for now :)

**Comment by AndrewBogdanovTSS** [comment]
It was more a test to make sure the latest beta isn't affected by any side effects 1.4.4 could create
